Feature: Validate Add Device Profile Functionality

  Scenario Outline: Validate Add Device Profile Functionality
    Given Go to Add Device Profile window
    When Enter Device Profile Name <DeviceProfileName>
    And Enter Version <Version>
    And Select Door Type <DoorType>
    And Enter Firmware Range From <RangeFrom>
    And Enter Firmware Range TO <RangeTo>
    And Upload Data Command Group JSON <DataCommandGroupJSON>
    And Upload Boot Command Group JSON <BootCommandGroupJSON>
    And Click on Submit button
    Then Verify Toaster Message for Add Device Profile <ExpMsg>

    Examples: 
      | DeviceProfileName               | Version         | DoorType       | RangeFrom    | RangeTo   | DataCommandGroupJSON                                   | BootCommandGroupJSON                                   | ExpMsg                                                     |
      | "Testing DPName"                | "123"           | "Sliding Door" | "123.432"    | "123.456" | "C:\\Users\\deepa\\Downloads\\data_command_group.json" | "C:\\Users\\deepa\\Downloads\\boot_command_group.json" | "Device Profile Added Successfully"                        |
      | "2354"                          | "12345"         | "Sliding Door" | "123.4"      | "123.45"  | "C:\\Users\\deepa\\Downloads\\data_command_group.json" | "C:\\Users\\deepa\\Downloads\\boot_command_group.json" | "Device Profile Added Successfully"                        |
      | "@@@$$$"                        | "548"           | "Sliding Door" | "123.4"      | "123.456" | "C:\\Users\\deepa\\Downloads\\data_command_group.json" | "C:\\Users\\deepa\\Downloads\\boot_command_group.json" | "Device Profile Added Successfully"                        |
      | "Testing13"                     | "145"           | "Swing Door"   | "123.432"    | "123.456" | "C:\\Users\\deepa\\Downloads\\data_command_group.json" | "C:\\Users\\deepa\\Downloads\\boot_command_group.json" | "Device Profile Added Successfully"                        |
      | "Testing1245@@"                 | "1345"          | "Rotary Door"  | "123.432"    | "123.456" | "C:\\Users\\deepa\\Downloads\\data_command_group.json" | "C:\\Users\\deepa\\Downloads\\boot_command_group.json" | "Device Profile Added Successfully"                        |
      | "14532$%@@"                     | "12345"         | "Sliding Door" | "123"        | "153.4"   | "C:\\Users\\deepa\\Downloads\\data_command_group.json" | "C:\\Users\\deepa\\Downloads\\boot_command_group.json" | "Device Profile Added Successfully"                        |
      | ""                              | "VERSION"       | "Sliding Door" | "123.4"      | "123.45"  | "C:\\Users\\deepa\\Downloads\\data_command_group.json" | "C:\\Users\\deepa\\Downloads\\boot_command_group.json" | "Submit Button is Disabled. Need to fill Mandatory fields" |
      | "     "                         | "24"            | "Sliding Door" | "123.4"      | "123.45"  | "C:\\Users\\deepa\\Downloads\\data_command_group.json" | "C:\\Users\\deepa\\Downloads\\boot_command_group.json" | "Duplicate Value Entered"                                  |
      | "Testing Version"               | "12345"         | "Swing Door"   | "123.42"     | "123.46"  | "C:\\Users\\deepa\\Downloads\\data_command_group.json" | "C:\\Users\\deepa\\Downloads\\boot_command_group.json" | "Device Profile Added Successfully"                        |
      | "Testing Version"               | "####"          | "Sliding Door" | "123.432"    | "125"     | "C:\\Users\\deepa\\Downloads\\data_command_group.json" | "C:\\Users\\deepa\\Downloads\\boot_command_group.json" | "Duplicate Value Entered"                                  |
      | "Testing Version"               | "ABC12345"      | "Sliding Door" | "123.43"     | "123.456" | "C:\\Users\\deepa\\Downloads\\data_command_group.json" | "C:\\Users\\deepa\\Downloads\\boot_command_group.json" | "Duplicate Value Entered"                                  |
      | "Testing Version"               | "VER##@@"       | "Sliding Door" | "123.4"      | "123.456" | "C:\\Users\\deepa\\Downloads\\data_command_group.json" | "C:\\Users\\deepa\\Downloads\\boot_command_group.json" | "Duplicate Value Entered"                                  |
      | "Testing Version"               | "345$$$$"       | "Rotary Door"  | "123.432"    | "123.6"   | "C:\\Users\\deepa\\Downloads\\data_command_group.json" | "C:\\Users\\deepa\\Downloads\\boot_command_group.json" | "Duplicate Value Entered"                                  |
      | "Testing Version"               | "VERSION"       | "Sliding Door" | "123.4"      | "123.45"  | "C:\\Users\\deepa\\Downloads\\data_command_group.json" | "C:\\Users\\deepa\\Downloads\\boot_command_group.json" | "Duplicate Value Entered"                                  |
      | "Testing Version"               | "VERsion"       | "Sliding Door" | "123.4"      | "123.456" | "C:\\Users\\deepa\\Downloads\\data_command_group.json" | "C:\\Users\\deepa\\Downloads\\boot_command_group.json" | "Duplicate Value Entered"                                  |
      | "Testing34@@"                   | "version"       | "Sliding Door" | "123.4"      | "123.456" | "C:\\Users\\deepa\\Downloads\\data_command_group.json" | "C:\\Users\\deepa\\Downloads\\boot_command_group.json" | "Duplicate Value Entered"                                  |
      | "Testing Data Command"          | "548"           | "Sliding Door" | "458.22"     | "123.45"  | "C:\\Users\\deepa\\Downloads\\Image.bmp"               | "C:\\Users\\deepa\\Downloads\\boot_command_group.json" | "Duplicate Value Entered"                                  |
      | "Testing Boot Command"          | "548"           | "Sliding Door" | "458.22"     | "123.45"  | "C:\\Users\\deepa\\Downloads\\data_command_group.json" | "C:\\Users\\deepa\\Downloads\\Image.bmp"               | "Duplicate Value Entered"                                  |
      | "Testing Data & Boot Command"   | "548"           | "Sliding Door" | "58"         | "123.45"  | "C:\\Users\\deepa\\Downloads\\DoorTypeDD.png"          | "C:\\Users\\deepa\\Downloads\\DoorTypeDD.png"          | "Duplicate Value Entered"                                  |
      | "Testing Data & Boot Command"   | "548"           | "Sliding Door" | "58"         | "123.45"  | "C:\\Users\\deepa\\Downloads\\data_command_group.json" | "C:\\Users\\deepa\\Downloads\\boot_command_group.json" | "Device Profile Added Successfully"                        |
      | "Testing Version"               | "VERsion123###" | "Sliding Door" | "123.4"      | "123.45"  | "C:\\Users\\deepa\\Downloads\\data_command_group.json" | "C:\\Users\\deepa\\Downloads\\boot_command_group.json" | "Duplicate Value Entered"                                  |
      | "Testing34@@"                   | ""              | "Sliding Door" | "123.4"      | "123.45"  | "C:\\Users\\deepa\\Downloads\\data_command_group.json" | "C:\\Users\\deepa\\Downloads\\boot_command_group.json" | "Submit Button is Disabled. Need to fill Mandatory fields" |
      | "Testing34@@"                   | "   "           | "Sliding Door" | "123.4"      | "123.45"  | "C:\\Users\\deepa\\Downloads\\data_command_group.json" | "C:\\Users\\deepa\\Downloads\\boot_command_group.json" | "Duplicate Value Entered"                                  |
      | "Testing Sliding Door"          | "145"           | "Sliding Door" | "123.432"    | "123.456" | "C:\\Users\\deepa\\Downloads\\data_command_group.json" | "C:\\Users\\deepa\\Downloads\\boot_command_group.json" | "Device Profile Added Successfully"                        |
      | "Testing Swing Door"            | "145"           | "Swing Door"   | "123.432"    | "123.456" | "C:\\Users\\deepa\\Downloads\\data_command_group.json" | "C:\\Users\\deepa\\Downloads\\boot_command_group.json" | "Device Profile Added Successfully"                        |
      | "Testing Rotary Door"           | "145"           | "Rotary Door"  | "123.432"    | "123.456" | "C:\\Users\\deepa\\Downloads\\data_command_group.json" | "C:\\Users\\deepa\\Downloads\\boot_command_group.json" | "Device Profile Added Successfully"                        |
      | "Testing Version"               | "145.234"       | "Rotary Door"  | "123.432"    | "123.456" | "C:\\Users\\deepa\\Downloads\\data_command_group.json" | "C:\\Users\\deepa\\Downloads\\boot_command_group.json" | "Duplicate Value Entered"                                  |
      | "Testing Firmware Range From"   | "145"           | "Rotary Door"  | "123.34"     | "123.456" | "C:\\Users\\deepa\\Downloads\\data_command_group.json" | "C:\\Users\\deepa\\Downloads\\boot_command_group.json" | "Device Profile Added Successfully"                        |
      | "Testing Firmware Range From"   | "145"           | "Rotary Door"  | "RANGE"      | "123.456" | "C:\\Users\\deepa\\Downloads\\data_command_group.json" | "C:\\Users\\deepa\\Downloads\\boot_command_group.json" | "Duplicate Value Entered"                                  |
      | "Testing Firmware Range From"   | "145"           | "Rotary Door"  | "range"      | "123.456" | "C:\\Users\\deepa\\Downloads\\data_command_group.json" | "C:\\Users\\deepa\\Downloads\\boot_command_group.json" | "Duplicate Value Entered"                                  |
      | "Testing Firmware Range From"   | "145"           | "Rotary Door"  | "&&&&&"      | "123.456" | "C:\\Users\\deepa\\Downloads\\data_command_group.json" | "C:\\Users\\deepa\\Downloads\\boot_command_group.json" | "Duplicate Value Entered"                                  |
      | "Testing Firmware Range From"   | "145"           | "Rotary Door"  | "Range&&&&&" | "123.456" | "C:\\Users\\deepa\\Downloads\\data_command_group.json" | "C:\\Users\\deepa\\Downloads\\boot_command_group.json" | "Duplicate Value Entered"                                  |
      | "Testing Firmware Range From"   | "145"           | "Rotary Door"  | "1234&&&&&"  | "123.456" | "C:\\Users\\deepa\\Downloads\\data_command_group.json" | "C:\\Users\\deepa\\Downloads\\boot_command_group.json" | "Duplicate Value Entered"                                  |
      | "Testing Firmware Range From"   | "145"           | "Rotary Door"  | "Range123"   | "123.456" | "C:\\Users\\deepa\\Downloads\\data_command_group.json" | "C:\\Users\\deepa\\Downloads\\boot_command_group.json" | "Duplicate Value Entered"                                  |
      | "Testing Firmware Range From 1" | "145"           | "Rotary Door"  | "25"         | "123.456" | "C:\\Users\\deepa\\Downloads\\data_command_group.json" | "C:\\Users\\deepa\\Downloads\\boot_command_group.json" | "Device Profile Added Successfully"                        |
