Feature: Validate Add Device Profile Functionality

  Scenario Outline: Validate Add Device Profile Functionality
    Given Go to Add Device Profile window
    When Enter Device Profile Name <DeviceProfileName>
    And Enter Version <Version>
    And Select Door Type <DoorType>
    And Enter Firmware Range From <RangeFrom>
    And Enter Firmware Range TO <RangeTo>
    And Upload Data Command Group JSON <DataCommandGroupJSON>
    And Upload Boot Command Group JSON <BootCommandGroupJSON>
    And Click on Submit button
    Then Verify Toaster Message for Add Device Profile <ExpMsg>

    Examples: 
      | DeviceProfileName                   | Version         | DoorType       | RangeFrom    | RangeTo   | DataCommandGroupJSON                                   | BootCommandGroupJSON                                   | ExpMsg                                                     |
      | "Testing DPName"                    | "123"           | "Sliding Door" | "123.432"    | "123.456" | "/home/vassar-deepa/Downloads/data_command_group.json" | "/home/vassar-deepa/Downloads/boot_command_group.json" | "Device Profile Added Successfully"                        |
      | "2354"                              | "12345"         | "Sliding Door" | "123.4"      | "123.45"  | "/home/vassar-deepa/Downloads/data_command_group.json" | "/home/vassar-deepa/Downloads/boot_command_group.json" | "Submit Button is Disabled. Need to fill Mandatory fields" |
      | "@@@$$$"                            | "548"           | "Sliding Door" | "123.4"      | "123.456" | "/home/vassar-deepa/Downloads/data_command_group.json" | "/home/vassar-deepa/Downloads/boot_command_group.json" | "Submit Button is Disabled. Need to fill Mandatory fields" |
      | "Testing DP Name 13"                | "145"           | "Swing Door"   | "123.432"    | "123.456" | "/home/vassar-deepa/Downloads/data_command_group.json" | "/home/vassar-deepa/Downloads/boot_command_group.json" | "Device Profile Added Successfully"                        |
      | "Testing DP Name One 1245@@"        | "1345"          | "Rotary Door"  | "123.432"    | "123.456" | "/home/vassar-deepa/Downloads/data_command_group.json" | "/home/vassar-deepa/Downloads/boot_command_group.json" | "Device Profile Added Successfully"                        |
      | "14532$%@@"                         | "12345"         | "Sliding Door" | "123"        | "153.4"   | "/home/vassar-deepa/Downloads/data_command_group.json" | "/home/vassar-deepa/Downloads/boot_command_group.json" | "Submit Button is Disabled. Need to fill Mandatory fields" |
      | ""                                  | "VERSION"       | "Sliding Door" | "123.4"      | "123.45"  | "/home/vassar-deepa/Downloads/data_command_group.json" | "/home/vassar-deepa/Downloads/boot_command_group.json" | "Submit Button is Disabled. Need to fill Mandatory fields" |
      | "     "                             | "24"            | "Sliding Door" | "123.4"      | "123.45"  | "/home/vassar-deepa/Downloads/data_command_group.json" | "/home/vassar-deepa/Downloads/boot_command_group.json" | "Duplicate Value Entered"                                  |
      | "Testing Version"                   | "12345"         | "Swing Door"   | "123.42"     | "123.46"  | "/home/vassar-deepa/Downloads/data_command_group.json" | "/home/vassar-deepa/Downloads/boot_command_group.json" | "Device Profile Added Successfully"                        |
      | "Testing Version"                   | "####"          | "Sliding Door" | "123.432"    | "125"     | "/home/vassar-deepa/Downloads/data_command_group.json" | "/home/vassar-deepa/Downloads/boot_command_group.json" | "Submit Button is Disabled. Need to fill Mandatory fields" |
      | "Testing Version One"               | "ABC12345"      | "Sliding Door" | "123.43"     | "123.456" | "/home/vassar-deepa/Downloads/data_command_group.json" | "/home/vassar-deepa/Downloads/boot_command_group.json" | "Device Profile Added Successfully"                        |
      | "Testing Version"                   | "VER##@@"       | "Sliding Door" | "123.4"      | "123.456" | "/home/vassar-deepa/Downloads/data_command_group.json" | "/home/vassar-deepa/Downloads/boot_command_group.json" | "Submit Button is Disabled. Need to fill Mandatory fields" |
      | "Testing Version"                   | "345$$$$"       | "Rotary Door"  | "123.432"    | "123.6"   | "/home/vassar-deepa/Downloads/data_command_group.json" | "/home/vassar-deepa/Downloads/boot_command_group.json" | "Submit Button is Disabled. Need to fill Mandatory fields" |
      | "Testing Version"                   | "VERSION"       | "Sliding Door" | "123.4"      | "123.45"  | "/home/vassar-deepa/Downloads/data_command_group.json" | "/home/vassar-deepa/Downloads/boot_command_group.json" | "Submit Button is Disabled. Need to fill Mandatory fields" |
      | "Testing Version"                   | "VERsion"       | "Sliding Door" | "123.4"      | "123.456" | "/home/vassar-deepa/Downloads/data_command_group.json" | "/home/vassar-deepa/Downloads/boot_command_group.json" | "Submit Button is Disabled. Need to fill Mandatory fields" |
      | "Testing Version Two"               | "VERsion123###" | "Sliding Door" | "123.4"      | "123.45"  | "/home/vassar-deepa/Downloads/data_command_group.json" | "/home/vassar-deepa/Downloads/boot_command_group.json" | "Device Profile Added Successfully"                        |
      | "Testing Version"                   | "145.234"       | "Rotary Door"  | "123.432"    | "123.456" | "/home/vassar-deepa/Downloads/data_command_group.json" | "/home/vassar-deepa/Downloads/boot_command_group.json" | "Duplicate Value Entered"                                  |
      | "Testing34@@"                       | "version"       | "Sliding Door" | "123.4"      | "123.456" | "/home/vassar-deepa/Downloads/data_command_group.json" | "/home/vassar-deepa/Downloads/boot_command_group.json" | "Submit Button is Disabled. Need to fill Mandatory fields" |
      | "Testing Data Command"              | "548"           | "Sliding Door" | "458.22"     | "580"     | "/home/vassar-deepa/Downloads/Image.bmp"               | "/home/vassar-deepa/Downloads/boot_command_group.json" | "Submit Button is Disabled. Need to fill Mandatory fields" |
      | "Testing Boot Command"              | "548"           | "Sliding Door" | "458.22"     | "500"     | "/home/vassar-deepa/Downloads/data_command_group.json" | "/home/vassar-deepa/Downloads/Image.bmp"               | "Submit Button is Disabled. Need to fill Mandatory fields" |
      | "Testing Data And Boot Command"     | "548"           | "Sliding Door" | "58"         | "123.45"  | "/home/vassar-deepa/Downloads/DoorTypeDD.png"          | "/home/vassar-deepa/Downloads/DoorTypeDD.png"          | "Submit Button is Disabled. Need to fill Mandatory fields" |
      | "Testing Data And Boot Command"     | "548"           | "Sliding Door" | "58"         | "123.45"  | "/home/vassar-deepa/Downloads/data_command_group.json" | "/home/vassar-deepa/Downloads/boot_command_group.json" | "Device Profile Added Successfully"                        |
      | "Testing34@@"                       | ""              | "Sliding Door" | "123.4"      | "123.45"  | "/home/vassar-deepa/Downloads/data_command_group.json" | "/home/vassar-deepa/Downloads/boot_command_group.json" | "Submit Button is Disabled. Need to fill Mandatory fields" |
      | "Testing34@@"                       | "   "           | "Sliding Door" | "123.4"      | "123.45"  | "/home/vassar-deepa/Downloads/data_command_group.json" | "/home/vassar-deepa/Downloads/boot_command_group.json" | "Duplicate Value Entered"                                  |
      | "Testing Sliding Door"              | "145"           | "Sliding Door" | "123.432"    | "123.456" | "/home/vassar-deepa/Downloads/data_command_group.json" | "/home/vassar-deepa/Downloads/boot_command_group.json" | "Device Profile Added Successfully"                        |
      | "Testing Swing Door"                | "145"           | "Swing Door"   | "123.432"    | "123.456" | "/home/vassar-deepa/Downloads/data_command_group.json" | "/home/vassar-deepa/Downloads/boot_command_group.json" | "Device Profile Added Successfully"                        |
      | "Testing Rotary Door"               | "145"           | "Rotary Door"  | "123.432"    | "123.456" | "/home/vassar-deepa/Downloads/data_command_group.json" | "/home/vassar-deepa/Downloads/boot_command_group.json" | "Device Profile Added Successfully"                        |
      | "Testing Firmware Range From"       | "145"           | "Rotary Door"  | "123.34"     | "123.456" | "/home/vassar-deepa/Downloads/data_command_group.json" | "/home/vassar-deepa/Downloads/boot_command_group.json" | "Device Profile Added Successfully"                        |
      | "Testing Firmware Range From"       | "145"           | "Rotary Door"  | "RANGE"      | "123.456" | "/home/vassar-deepa/Downloads/data_command_group.json" | "/home/vassar-deepa/Downloads/boot_command_group.json" | "Submit Button is Disabled. Need to fill Mandatory fields" |
      | "Testing Firmware Range From"       | "145"           | "Rotary Door"  | "range"      | "123.456" | "/home/vassar-deepa/Downloads/data_command_group.json" | "/home/vassar-deepa/Downloads/boot_command_group.json" | "Submit Button is Disabled. Need to fill Mandatory fields" |
      | "Testing Firmware Range From"       | "145"           | "Rotary Door"  | "&&&&&"      | "123.456" | "/home/vassar-deepa/Downloads/data_command_group.json" | "/home/vassar-deepa/Downloads/boot_command_group.json" | "Submit Button is Disabled. Need to fill Mandatory fields" |
      | "Testing Firmware Range From"       | "145"           | "Rotary Door"  | "Range&&&&&" | "123.456" | "/home/vassar-deepa/Downloads/data_command_group.json" | "/home/vassar-deepa/Downloads/boot_command_group.json" | "Submit Button is Disabled. Need to fill Mandatory fields" |
      | "Testing Firmware Range From One"   | "145"           | "Rotary Door"  | "1234&&&&&"  | "123.456" | "/home/vassar-deepa/Downloads/data_command_group.json" | "/home/vassar-deepa/Downloads/boot_command_group.json" | "Device Profile Added Successfully"                        |
      | "Testing Firmware Range From Two"   | "145"           | "Rotary Door"  | "Range123"   | "123.456" | "/home/vassar-deepa/Downloads/data_command_group.json" | "/home/vassar-deepa/Downloads/boot_command_group.json" | "Device Profile Added Successfully"                        |
      | "Testing Firmware Range From Three" | "145"           | "Rotary Door"  | "25"         | "123.456" | "/home/vassar-deepa/Downloads/data_command_group.json" | "/home/vassar-deepa/Downloads/boot_command_group.json" | "Device Profile Added Successfully"                        |
